### ISSUE TITLE
Headers mismatch

### ISSUE THREAD

**Issue by ziyadkafadi** [devine-dl/pywidevine#45]
Need help,

i got this error 
ERROR:license:[-] Failed to send challenge: [403] {"code":403,"message":"Headers mismatch"}

I think this need header for lic url, 
which folder to place headers.py ?

i use pywidevine version 1.8.0

**Comment by rlaphoenix** [comment]
Follow the [Usage Example in the README](https://github.com/devine-dl/pywidevine#usage) and add the headers you want to the `requests.post` call.
